language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - TESTER_PHP_BIN=php
    - TESTER_PHP_BIN=php-cgi

matrix:
    allow_failures:
        - php: hhvm

    exclude:
        - php: hhvm
          env: TESTER_PHP_BIN=php-cgi

install:
    - composer self-update

before_script:
    - composer update --no-interaction --dev

script:
    - ./vendor/nette/tester/Tester/tester tests -p $TESTER_PHP_BIN tests -s
    - ./vendor/squizlabs/php_codesniffer/scripts/phpcs ./src --standard=codestyle.xml -n

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

git:
    depth: 5